version = "1.2.8"
builder = "spa"

[template_settings]
text-color = "#c7cfcc"
accent-color = "#2D4566"
highlight-color = "#73bed3"
background-color = "#121414"
autoreload = "1"
custom-color = "#f3a833"
subheader-text = "SecureHub — curated cybersecurity news"
# To show a GitHub corner linking to your repo, uncomment the next line.
# repo-url = "https://github.com/krisbogaerts/news-securehub"
